"""Master comparison script.

Reads all experiments/EXP-*/metrics.json, produces:
  - experiments/COMPARISON.md (living leaderboard with CIs)
  - experiments/figures/operating_curves_all.png (master overlay with CI bands)
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import yaml


def setup_style():
    sns.set_theme(style="whitegrid", font_scale=1.1)
    plt.rcParams["figure.dpi"] = 150
    plt.rcParams["savefig.dpi"] = 300
    plt.rcParams["savefig.bbox"] = "tight"


def load_experiment(exp_dir: Path) -> dict | None:
    """Load metrics.json from an experiment directory."""
    metrics_path = exp_dir / "metrics.json"
    if not metrics_path.exists():
        return None
    with open(metrics_path) as f:
        return json.load(f)


def format_ci(point: float | None, ci_lo: float | None = None,
              ci_hi: float | None = None) -> str:
    """Format a value with optional CI."""
    if point is None:
        return "---"
    if ci_lo is not None and ci_hi is not None:
        return f"{point:.4f} [{ci_lo:.4f}, {ci_hi:.4f}]"
    return f"{point:.4f}"


def main():
    parser = argparse.ArgumentParser(description="Master comparison across experiments")
    parser.add_argument("--config", default="configs/default.yaml")
    args = parser.parse_args()

    with open(args.config) as f:
        cfg = yaml.safe_load(f)

    exp_base = Path(cfg["output"]["experiments_dir"])
    fig_dir = exp_base / "figures"
    fig_dir.mkdir(parents=True, exist_ok=True)

    # Discover all experiment directories
    exp_dirs = sorted(exp_base.glob("EXP-*"))
    print(f"Found {len(exp_dirs)} experiment directories")

    # Collect all triggers and their summaries across experiments
    all_triggers: dict[str, dict] = {}  # trigger_name -> best data

    for exp_dir in exp_dirs:
        data = load_experiment(exp_dir)
        if data is None:
            print(f"  Skipping {exp_dir.name}: no metrics.json")
            continue

        print(f"  Loading {exp_dir.name}")

        # Extract triggers from different experiment formats
        triggers_data = data.get("triggers", {})
        for trig_name, trig_data in triggers_data.items():
            key = f"{trig_name} ({exp_dir.name})"
            all_triggers[key] = {
                "experiment": exp_dir.name,
                "trigger": trig_name,
                "summary": trig_data.get("summary", {}),
                "bootstrap_ci": trig_data.get("bootstrap_ci", {}),
                "curve_bands": trig_data.get("curve_bands"),
                "scorecard_tau_0.00": trig_data.get("scorecard_tau_0.00", {}),
                "scorecard_tau_0.05": trig_data.get("scorecard_tau_0.05", {}),
            }

    if not all_triggers:
        print("No experiment data found. Run experiments first.")
        return

    # -----------------------------------------------------------------------
    # Generate COMPARISON.md
    # -----------------------------------------------------------------------
    lines = [
        "# Experiment Comparison (Living Leaderboard)",
        "",
        f"*Auto-generated by `scripts/compare.py`. {len(all_triggers)} trigger entries.*",
        "",
    ]

    # Summary table
    lines.extend([
        "## Operating Curve Summary",
        "",
        "| Trigger | Experiment | netWER@10% | netWER@20% | netWER@30% | netWER@50% | Area vs Random |",
        "|---------|-----------|------------|------------|------------|------------|---------------|",
    ])

    for key, tdata in sorted(all_triggers.items(), key=lambda x: x[1]["trigger"]):
        summary = tdata["summary"]
        ci = tdata.get("bootstrap_ci", {})

        def _fmt(metric_key: str) -> str:
            point = summary.get(metric_key)
            ci_data = ci.get(metric_key, {})
            return format_ci(point, ci_data.get("ci_lo"), ci_data.get("ci_hi"))

        row = (
            f"| {tdata['trigger']} | {tdata['experiment']} "
            f"| {_fmt('net_wer_at_10pct')} "
            f"| {_fmt('net_wer_at_20pct')} "
            f"| {_fmt('net_wer_at_30pct')} "
            f"| {_fmt('net_wer_at_50pct')} "
            f"| {_fmt('area_vs_random')} |"
        )
        lines.append(row)

    # Decision scorecard table
    lines.extend([
        "",
        "## Decision Scorecard",
        "",
        "| Trigger | Experiment | AUC (tau=0) | AP (tau=0) | AUC (tau=0.05) | AP (tau=0.05) | Pearson r | Spearman r |",
        "|---------|-----------|-------------|-----------|----------------|--------------|-----------|-----------|",
    ])

    for key, tdata in sorted(all_triggers.items(), key=lambda x: x[1]["trigger"]):
        sc0 = tdata.get("scorecard_tau_0.00", {})
        sc05 = tdata.get("scorecard_tau_0.05", {})

        def _fv(v):
            return f"{v:.4f}" if v is not None else "---"

        row = (
            f"| {tdata['trigger']} | {tdata['experiment']} "
            f"| {_fv(sc0.get('auc'))} "
            f"| {_fv(sc0.get('ap'))} "
            f"| {_fv(sc05.get('auc'))} "
            f"| {_fv(sc05.get('ap'))} "
            f"| {_fv(sc0.get('pearson_r'))} "
            f"| {_fv(sc0.get('spearman_r'))} |"
        )
        lines.append(row)

    lines.append("")

    comparison_path = exp_base / "COMPARISON.md"
    with open(comparison_path, "w") as f:
        f.write("\n".join(lines))
    print(f"\nSaved: {comparison_path}")

    # -----------------------------------------------------------------------
    # Master overlay figure with CI bands
    # -----------------------------------------------------------------------
    setup_style()
    fig, ax = plt.subplots(figsize=(12, 8))

    # Style palette for triggers
    trigger_styles = {
        "oracle": {"color": "green", "linestyle": "-", "linewidth": 2, "alpha": 0.8},
        "scalar_probe": {"color": "blue", "linestyle": "-", "linewidth": 2.5, "alpha": 1.0},
        "argmax_accent": {"color": "orange", "linestyle": "--", "linewidth": 2, "alpha": 0.8},
        "confidence": {"color": "purple", "linestyle": "-.", "linewidth": 1.5, "alpha": 0.7},
        "random": {"color": "gray", "linestyle": ":", "linewidth": 1.5, "alpha": 0.6},
        "probe_gain": {"color": "red", "linestyle": "-", "linewidth": 2.5, "alpha": 1.0},
        "probe_capped_wer": {"color": "cyan", "linestyle": "--", "linewidth": 2, "alpha": 0.8},
        "compression_ratio": {"color": "brown", "linestyle": "-.", "linewidth": 1.5, "alpha": 0.7},
        "no_speech_prob": {"color": "pink", "linestyle": ":", "linewidth": 1.5, "alpha": 0.7},
        "probe_mean_std": {"color": "darkred", "linestyle": "-", "linewidth": 2.5, "alpha": 1.0},
        "probe_mean_only": {"color": "darkblue", "linestyle": "--", "linewidth": 2, "alpha": 0.8},
        "probe_std_only": {"color": "darkgreen", "linestyle": "-.", "linewidth": 1.5, "alpha": 0.7},
    }

    plotted = set()
    for key, tdata in sorted(all_triggers.items()):
        trig_name = tdata["trigger"]
        bands = tdata.get("curve_bands")
        if bands is None:
            continue

        # Avoid plotting the same trigger from the same experiment twice
        plot_key = f"{trig_name}_{tdata['experiment']}"
        if plot_key in plotted:
            continue
        plotted.add(plot_key)

        rates = np.array(bands["escalation_rates"])
        wers_point = np.array(bands["net_wers_point"])
        order = np.argsort(rates)

        style = trigger_styles.get(trig_name,
                                   {"color": "black", "linestyle": "-", "linewidth": 1})
        label = f"{trig_name} ({tdata['experiment']})"
        ax.plot(rates[order], wers_point[order], label=label, **style)

        # CI bands
        if "net_wers_ci_lo" in bands and "net_wers_ci_hi" in bands:
            ci_lo = np.array(bands["net_wers_ci_lo"])
            ci_hi = np.array(bands["net_wers_ci_hi"])
            ax.fill_between(rates[order], ci_lo[order], ci_hi[order],
                            alpha=0.1, color=style.get("color", "black"))

    ax.set_xlabel("Escalation Rate")
    ax.set_ylabel("Net WER (capped)")
    ax.set_title("Master Operating Curve Comparison (with 95% CI bands)")
    ax.legend(fontsize=7, loc="upper right")
    ax.set_xlim(0, 1)

    fig.tight_layout()
    fig.savefig(fig_dir / "operating_curves_all.png")
    plt.close(fig)
    print(f"Saved: {fig_dir / 'operating_curves_all.png'}")


if __name__ == "__main__":
    main()
